#!/bin/bash

#cat  wrappedhl | sudo tee ~/wrappedhl
#cat .bash_profile | sudo tee  ~/.bash_profile
sudo mkdir /etc/sddm.conf.d
cat 00-hyprland.conf | sudo tee /etc/sddm.conf.d/00-hyprland.conf
sudo sed -i 's/kb_layout = us/kb_layout = fr/' ~/.config/hypr/hyprland.conf
sudo sed -i 's/autogenerated = 1 # remove this line to remove the warning//' ~/.config/hypr/hyprland.conf
sudo sed -i 's/bind = $mainMod, C, killactive,/bind = $mainMod, W, killactive,/' ~/.config/hypr/hyprland.conf
sudo sed -i 's/$menu = wofi --show drun/$menu = rofi -show drun/' ~/.config/hypr/hyprland.conf
sudo sed -i 's/bind = $mainMod, R,/bind = $mainMod, F,/' ~/.config/hypr/hyprland.conf

#theme sddm
git clone siddrs/tokyo-night-sddm ~/usr/share/sddm/themes/
sudo cp -i /usr/lib/sddm/sddm.conf.d/default.conf /etc/sddm.conf
sudo sed -i 's/User=/User=gamovek/' /etc/sddm.conf
sudo sed -i 's/Current=/Current=tokyo-night-sddm/' /etc/sddm.conf
