#!/bin/bash
sudo pacman -Syu
sudo pacman -S base-devel linux-headers --noconfirm
sudo pacman -S hyprland kitty gtk3 rofi-wayland dolphin sddm sddm-kcm git nano--noconfirm
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si --noconfirm
echo wrappedhl > ~/wrappedhl
echo .bash_profile > ~/.bash_profile
echo 00-hyprland.conf > /etc/sddm.conf.d/00-hyprland.conf
sudo sed -i 's/kb_layout = us/kb_layout = fr/' ~/.config/hypr/hyprland.conf
sudo sed -i 's/autogenerated = 1 # remove this line to remove the warning//' ~/.config/hypr/hyprl
and.conf
sudo systemctl enable sddm
sudo reboot 
