#!/bin/sh
cd ~
export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=24
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=ibus

# Paramètres pour les applications Qt
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORM="wayland"
export QT_QPA_PLATFORMTHEME=qt5ct

#swaylock
cd $HOME/pic/wallpapers && swaybg -m fill -i $(ls *.jpg | shuf | head -n 1) &


# Paramètres pour GTK
# gsettings set org.gnome.desktop.interface icon-theme 'Win11-dark'
# gsettings set org.gnome.desktop.interface gtk-theme 'Gruvbox-Dark-BL'
# gsettings set org.gnome.desktop.interface cursor-theme 'WhiteSur Cursors'
# gsettings set org.gnome.desktop.interface font-name 'JetBrains Mono NL SemiBold'
# Active le verrouillage numérique
setleds +num

exec Hyprland
